# file: roles/wetty/defaults/main.yml
---


openssl_self_signed:
  - name: '{{ domain_name }}'
    domains: ['*.{{ domain_name }}', '{{ domain_name }}']
    country: 'US'
    state: 'VA'
    city: 'Tysons'
    organization: 'Red Hat'
    unit: 'Public Sector'
    email: 'bsollar@redhat.com'
    days: 3650


key_path:   "home/{{ ansible_user }}/.wetty/privkey.pem"
cert_path:  "home/{{ ansible_user }}/.wetty/cert.pem"
wetty_port:  8888
wetty_user: "azure-user" # "cockpit"
