- name: grab facts for control_nodes
  azure_rm_virtualmachine_facts:
    resource_group: "{{azure_name_prefix}}"
    tags:
      - Workshop_ansible
  register: ansible_node_facts

- debug: var=ansible_node_facts

- name: add ansible node to control_nodes group
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    student: "{{ item.tags.Student }}"
    short_name: "ansible"
    ansible_host: "{{ item.tags.public_ip_address }}"
    ansible_user: "{{ item.tags.Student }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_pass: "{{ admin_password }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{azure_name_prefix}}/{{azure_name_prefix}}-private.pem"
    private_ip: "{{item.tags.private_ip_address}}"
    groups:
      - control_nodes
  with_items: "{{ ansible_node_facts.vms }}"
